# Generated by Django 4.2.7 on 2024-03-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('pu', 'Public'), ('un', 'Unlisted'), ('pr', 'Private')], default='pu', max_length=155),
        ),
    ]
