# Generated by Django 4.2.7 on 2025-03-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='earning',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
