# Generated by Django 4.2.7 on 2025-04-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_parent'),
        ('items', '0007_remove_product_earning_product_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='categories.category'),
        ),
    ]
