# Generated by Django 4.2.7 on 2025-04-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_alter_category_parent'),
        ('items', '0008_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='categories.category'),
        ),
    ]
