# Generated by Django 4.2.3 on 2025-12-14 20:32

import apps.items.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_product_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=100, scale=1, size=[1920, 1080], upload_to=apps.items.models.image_path),
        ),
    ]
