# Generated by Django 6.0 on 2026-01-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
