# Generated by Django 6.0 on 2026-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_productimage_alt_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='profit',
            field=models.IntegerField(blank=True, default=10, help_text='Enter the profit percentage, e.g., 10', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='visibility',
            field=models.CharField(choices=[('pu', 'Public'), ('un', 'Unlisted'), ('pr', 'Private')], default='pu', max_length=2),
        ),
    ]
