# Generated by Django 4.2.7 on 2024-05-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_date_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'Shipped'), ('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled'), ('P_SHIPPED', 'Partially shipped'), ('OTHER', 'Not confirmed')], default='OTHER', max_length=155),
        ),
    ]
