# Generated by Django 4.2.7 on 2024-07-26 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_payment_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='ready_to_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=0),
        ),
    ]
