# Generated by Django 6.0 on 2026-01-28 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_cart_cart_total_remove_cart_ready_to_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CH', 'Cash'), ('DT', 'Debit'), ('CT', 'Credit')], max_length=2),
        ),
    ]
