# Generated by Django 6.0 on 2026-01-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
