# Generated by Django 4.2.7 on 2024-10-13 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_trending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='trending_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
