# Generated by Django 6.0 on 2026-01-20 02:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_post_is_trending_post_trending_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_likes',
            field=models.ManyToManyField(through='news.CommentLike', through_fields=('comment', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_dislikes',
            field=models.ManyToManyField(related_name='user_disliked_posts', through='news.Dislike', through_fields=('post', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_likes',
            field=models.ManyToManyField(related_name='user_liked_posts', through='news.Like', through_fields=('post', 'user'), to=settings.AUTH_USER_MODEL),
        ),
    ]
