# Generated by Django 4.2.7 on 2024-10-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='earning',
            field=models.IntegerField(default=0.1),
        ),
    ]
