# Generated by Django 4.2.7 on 2024-11-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_membership_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='earning',
            field=models.IntegerField(default=10),
        ),
    ]
