# Generated by Django 4.2.7 on 2025-03-20 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0003_alter_membership_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='earning',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
