# Generated by Django 4.2.7 on 2025-04-11 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_alter_membership_earning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='earning',
        ),
        migrations.AddField(
            model_name='membership',
            name='profit',
            field=models.IntegerField(blank=True, default=10, help_text='Enter the profit percentage, for example 10%', null=True),
        ),
    ]
