# Generated by Django 6.0 on 2026-01-20 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_remove_membership_earning_membership_profit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='final_price',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
