# Generated by Django 6.0 on 2026-02-26 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0007_alter_membership_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='profit',
            field=models.IntegerField(blank=True, default=10, help_text='Enter the profit percentage, e.g., 10', null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
