# Generated by Django 4.2.7 on 2025-03-22 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0006_alter_product_earning'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_factor', models.CharField(choices=[('Mid Tower', 'Mid Tower'), ('Full Tower', 'Full Tower'), ('Mini Tower', 'Mini Tower'), ('ITX', 'ITX')], max_length=50)),
                ('motherboard_support', models.CharField(help_text='Compatible motherboard sizes', max_length=100)),
                ('material', models.CharField(help_text='Materials used in the case', max_length=100)),
                ('fan_support', models.CharField(help_text='Number and placement of supported fans', max_length=255)),
                ('radiator_support', models.CharField(help_text='Maximum supported radiator sizes', max_length=255)),
                ('gpu_clearance', models.PositiveSmallIntegerField(help_text='Maximum GPU length in mm')),
                ('cpu_cooler_clearance', models.PositiveSmallIntegerField(help_text='Maximum CPU cooler height in mm')),
                ('psu_clearance', models.PositiveSmallIntegerField(help_text='Maximum PSU length in mm')),
                ('rgb_lighting', models.BooleanField(default=False, help_text='Does the case have built-in RGB lighting?')),
                ('front_panel_io', models.TextField(help_text='List of front panel ports and buttons')),
                ('dimensions', models.CharField(help_text='Case dimensions (WxDxH)', max_length=50)),
                ('weight', models.FloatField(help_text='Weight of the case in kg')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='case_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'Case Specification',
                'verbose_name_plural': 'Case Specifications',
            },
        ),
        migrations.CreateModel(
            name='CoolerSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Air Cooler', 'Air Cooler'), ('Liquid Cooler', 'Liquid Cooler')], max_length=50)),
                ('fan_size', models.PositiveSmallIntegerField(help_text='Size of the fan in mm')),
                ('max_rpm', models.PositiveSmallIntegerField(help_text='Maximum RPM of the fan')),
                ('noise_level', models.CharField(help_text='Noise level in dBA', max_length=20)),
                ('tdp_rating', models.PositiveSmallIntegerField(help_text='Maximum TDP supported (in Watts)')),
                ('compatibility', models.TextField(help_text='Supported CPU sockets (Intel/AMD)')),
                ('rgb_lighting', models.BooleanField(default=False, help_text='Does the cooler have RGB lighting?')),
                ('dimensions', models.CharField(help_text='Dimensions of the cooler (WxDxH)', max_length=50)),
                ('weight', models.PositiveSmallIntegerField(help_text='Weight in grams')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cooler_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'Cooler Specification',
                'verbose_name_plural': 'Cooler Specifications',
            },
        ),
        migrations.CreateModel(
            name='CPUSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cores', models.PositiveIntegerField(blank=True, null=True)),
                ('threads', models.PositiveIntegerField(blank=True, null=True)),
                ('base_clock', models.FloatField(blank=True, null=True)),
                ('boost_clock', models.FloatField(blank=True, null=True)),
                ('tdp', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cpu_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'CPU Spec',
                'verbose_name_plural': 'CPU Specs',
            },
        ),
        migrations.CreateModel(
            name='GPUSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vram', models.PositiveIntegerField(blank=True, null=True)),
                ('core_clock', models.FloatField(blank=True, null=True)),
                ('memory_bus', models.PositiveIntegerField(blank=True, null=True)),
                ('power_consumption', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gpu_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'GPU Spec',
                'verbose_name_plural': 'GPU Specs',
            },
        ),
        migrations.CreateModel(
            name='MotherboardSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chipset', models.CharField(blank=True, max_length=50, null=True)),
                ('socket', models.CharField(blank=True, max_length=20, null=True)),
                ('form_factor', models.CharField(blank=True, max_length=20, null=True)),
                ('max_memory', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory_slots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('memory_type', models.CharField(blank=True, max_length=20, null=True)),
                ('pci_express_slots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('m2_slots', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sata_ports', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('usb_ports', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('wifi', models.BooleanField(default=False)),
                ('bluetooth', models.BooleanField(default=False)),
                ('rgb_lighting', models.BooleanField(default=False)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'Motherboard Specification',
                'verbose_name_plural': 'Motherboard Specifications',
            },
        ),
        migrations.CreateModel(
            name='NetworkingSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ports', models.CharField(blank=True, max_length=255, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='networking_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'Networking Spec',
                'verbose_name_plural': 'Networking Specs',
            },
        ),
        migrations.CreateModel(
            name='StorageSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('read_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('write_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='storage_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'Storage Spec',
                'verbose_name_plural': 'Storage Specs',
            },
        ),
        migrations.CreateModel(
            name='RAMSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.PositiveIntegerField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ram_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'RAM Spec',
                'verbose_name_plural': 'RAM Specs',
            },
        ),
        migrations.CreateModel(
            name='PSUSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wattage', models.PositiveIntegerField(blank=True, null=True)),
                ('efficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='psu_specs', to='items.product')),
            ],
            options={
                'verbose_name': 'PSU Spec',
                'verbose_name_plural': 'PSU Specs',
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.casespecs')),
                ('cooling', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.coolerspecs')),
                ('cpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.cpuspecs')),
                ('gpu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.gpuspecs')),
                ('motherboard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.motherboardspecs')),
                ('networking', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.networkingspecs')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pc_specs', to='items.product')),
                ('psu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.psuspecs')),
                ('ram', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.ramspecs')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.storagespecs')),
            ],
            options={
                'verbose_name': 'PC',
                'verbose_name_plural': 'PCs',
            },
        ),
    ]
