# Generated by Django 4.2.7 on 2025-03-22 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='networking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.networkingspecs'),
        ),
        migrations.AlterField(
            model_name='psuspecs',
            name='efficiency',
            field=models.CharField(blank=True, choices=[('80+', '80 Plus'), ('80_Bronze', '80 Plus Bronze'), ('80_Silver', '80 Plus Silver'), ('80_Gold', '80 Plus Gold'), ('80_Platinum', '80 Plus Platinum'), ('80_Titanium', '80 Plus Titanium')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='storagespecs',
            name='type',
            field=models.CharField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD'), ('NVMe', 'NVMe')], max_length=50, null=True),
        ),
    ]
