# Generated by Django 4.2.7 on 2025-04-01 00:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0002_alter_pc_networking_alter_psuspecs_efficiency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='ram_quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(4, 'You can stack up to 4 ram sticks')]),
        ),
    ]
