# Generated by Django 4.2.7 on 2025-04-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0003_pc_ram_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='motherboardspecs',
            name='memory_channels',
            field=models.CharField(choices=[('SC', 'SINGLE-CHANNEL'), ('DC', 'DUAL-CHANNEL')], default='DC', max_length=20),
        ),
        migrations.AlterField(
            model_name='motherboardspecs',
            name='form_factor',
            field=models.CharField(blank=True, choices=[('ATX', 'STANDARD-ATX'), ('MCATX', 'MICRO-ATX'), ('MNATX', 'MINI-ATX'), ('NNATX', 'NANO-ATX')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='motherboardspecs',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('D4', 'DDR4'), ('D5', 'DDR5')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='motherboardspecs',
            name='socket',
            field=models.CharField(blank=True, choices=[('AM4', 'AM4'), ('AM5', 'AM5'), ('LGA12', 'LGA1200'), ('LGA1700', 'LGA1700')], max_length=20, null=True),
        ),
    ]
