# Generated by Django 4.2.7 on 2025-04-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0004_motherboardspecs_memory_channels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gpuspecs',
            old_name='core_clock',
            new_name='base_clock',
        ),
        migrations.AddField(
            model_name='gpuspecs',
            name='boost_clock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpuspecs',
            name='bus_interface',
            field=models.CharField(blank=True, choices=[('E4X16', 'PCIe 4.0 x16')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='gpuspecs',
            name='memory_clock',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpuspecs',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('G6', 'GDDR6')], max_length=20, null=True),
        ),
    ]
