# Generated by Django 4.2.7 on 2025-04-11 02:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0005_rename_core_clock_gpuspecs_base_clock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casespecs',
            name='color',
            field=models.CharField(choices=[('BL', 'Black'), ('WH', 'White')], default='BL', max_length=20),
        ),
        migrations.AddField(
            model_name='gpuspecs',
            name='color',
            field=models.CharField(choices=[('BL', 'Black'), ('WH', 'White')], default='BL', max_length=20),
        ),
        migrations.AddField(
            model_name='pc',
            name='aesthetics',
            field=models.PositiveIntegerField(help_text='Rate the aesthetics of the PC (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pc',
            name='performance',
            field=models.PositiveIntegerField(help_text='Rate the performance of the PC (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='pc',
            name='price',
            field=models.PositiveIntegerField(help_text='Rate the pricing fairness/value (1 to 5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='ramspecs',
            name='color',
            field=models.CharField(choices=[('BL', 'Black'), ('WH', 'White')], default='BL', max_length=20),
        ),
        migrations.AlterField(
            model_name='pc',
            name='gpu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pc_factory.gpuspecs'),
        ),
    ]
