# Generated by Django 4.2.7 on 2025-04-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0006_casespecs_color_gpuspecs_color_pc_aesthetics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coolerspecs',
            name='color',
            field=models.CharField(choices=[('BL', 'Black'), ('WH', 'White')], default='BL', max_length=20),
        ),
        migrations.AddField(
            model_name='ramspecs',
            name='rgb',
            field=models.BooleanField(default=False),
        ),
    ]
