# Generated by Django 4.2.7 on 2025-04-11 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0007_coolerspecs_color_ramspecs_rgb'),
    ]

    operations = [
        migrations.AddField(
            model_name='psuspecs',
            name='color',
            field=models.CharField(choices=[('BL', 'Black'), ('WH', 'White')], default='BL', max_length=20),
        ),
    ]
