# Generated by Django 4.2.7 on 2025-04-12 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_product_categories'),
        ('pc_factory', '0008_psuspecs_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pc',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='PC_specs', to='items.product'),
        ),
    ]
