# Generated by Django 4.2.7 on 2025-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0009_alter_pc_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessorySpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='gpuspecs',
            name='bus_interface',
            field=models.CharField(blank=True, choices=[('E4X16', 'PCIe 4.0 x16'), ('E5X16', 'PCIe 5.0 x16')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='gpuspecs',
            name='memory_type',
            field=models.CharField(blank=True, choices=[('G6', 'GDDR6'), ('G7', 'GDDR7')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ramspecs',
            name='type',
            field=models.CharField(blank=True, choices=[('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=50, null=True),
        ),
    ]
