# Generated by Django 4.2.7 on 2025-05-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pc_factory', '0010_accessoryspecs_alter_gpuspecs_bus_interface_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessorySpecs',
        ),
    ]
