# Generated by Django 4.2.7 on 2024-03-21 22:45

import apps.ecommerce.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('demo', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=100, scale=1, size=[1920, 1080], upload_to=apps.ecommerce.models.demo_loc)),
            ],
            options={
                'verbose_name_plural': 'Clothes',
            },
        ),
    ]
